name: 'Release new version'

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    environment: release
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v5

      - name: 'Set up JDK 21'
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          java-package: jdk

      - name: 'Set up git'
        run: git config user.email "${{ github.actor }}@users.noreply.github.com" && git config user.name "Github Actions"

      - name: 'Capture version number for release'
        run: |
          echo "VERSION=$(grep -v '^#' gradle.properties | grep 'version=' | cut -d '=' -f2 | xargs)" >> $GITHUB_ENV
          echo "COMMIT=$(echo ${{github.sha}} | cut -c 1-7)" >> $GITHUB_ENV

      - name: 'build and update version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build release -Prelease.useAutomaticVersion=true

      - name: 'Checkout release version'
        uses: actions/checkout@v5
        with:
          ref: "release-${{ env.VERSION }}"

      - name: 'Publish package'
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Generate release info'
        run: |
          echo "Releaset ${{env.COMMIT}} som ${{ env.VERSION }}" > release_info.txt

      - name: 'Upload release info'
        uses: actions/upload-artifact@v4
        with:
          name: release-info
          path: release_info.txt
          
